name: DEPLOY TO EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
            
          host: 13.51.173.199
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd CI-CD
            echo "Checking running process on port 3000..."
            sudo lsof -t -i:3000 | xargs -r kill -9
            git pull origin main

            echo "Installing dependencies..."
            npm install

            echo "Building the app..."
            npm run build

            echo "Starting the app... lolo"
            npm run start


      
